export const FETCH_JOB_BOARDS = "FETCH_JOB_BOARDS";
export const FETCH_JOB_BOARDS_SUCCESS = "FETCH_JOB_BOARDS_SUCCESS";
export const FETCH_JOB_BOARDS_FAILURE = "FETCH_JOB_BOARDS_FAILURE";

export const fetchJobBoards = () => ({ type: FETCH_JOB_BOARDS });
